sudo: required
language: node_js
node_js:
    - "stable"
branches:
    only:
        - master
matrix:
    fast_finish: true
cache:
    directories:
        - node_modules
before_script:
    - npm install -g @angular/cli
    - npm install -g firebase-tools
script:
    - npm ci
    - npm run test
    - npm run build
after_success:
    - firebase deploy --token $FIREBASE_TOKEN --non-interactive
deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: dist
    on:
        branch: master
